package pissening

var (
	overflowReplies = []string{
		"Uh oh! %s overfilled The Jar!",
		"Point and laugh at the bladder of shame %s.",
		"You have forsaken all by overfilling The Jar. Atone for your sin %s.",
		"Now look what you've done... %s!",
		"THE JAR HAS OVERFILLED. THE JAR HAS OVERFILLED. THIS IS NOT A DRILL. %s HAS OVERFILLED THE JAR",
	}
	pissReplies = []string{
		"The Jar calls. %s has answered.",
		"%s nobly adds one more.",
		"History will remember %s for their contribution.",
		"Are you afraid, %s? Afraid of what you have done?",
		"The Jar has been satiated by %s.",
		"%s silences the jar’s demands.",
		"%s cements the fate of those after it.",
		"The string of fate has been cut by %s.",
		"Do not be afraid, %s. It is for the best.",
		"You have done well, %s.",
		"%s ascends higher.",
		"%s becomes one with The Jar.",
		"Your sacrifice may be for naught, %s.",
		"Do you fear the ramifications, %s?",
		"Was that what The Jar wanted, %s?",
		"Was that the right move, %s?",
		"I sure hope that doesn’t have consequences later, %s.",
		"Damn that shit was like water! %s",
		"Strategic. Or maybe it wasn’t. %s",
		"Get fucked, other timezones. %s",
		"%s is personally making everyone’s lives a little harder.",
		"Outstanding move, %s.",
		"%s steps forth and conquers.",
		"Pee is no longer stored in the %s.",
		"This is the world’s weirdest game of chess. %s.",
		"%s generously adds to the counter.",
		"%s just fucks everyone over. Pure fuckery.",
		"That one might come back to bite you in the ass, %s.",
		"%s relief is temporary. Remember that.",
		"Everyone SHUT THE FUCK UP %s PEED",
		"Hold ALL of your horses %s just pissed",
		"Be afraid of %s.",
		"You ever think about where your life is at? %s",
		"What a world we live in. %s",
		"This one goes out to %s.",
		"E-piss received. %s",
		"Noted, %s.",
		"Good one, %s",
		"Oh man, I dunno about that one, %s.",
		"Risky move, %s.",
		"Heaven has fallen. %s",
		"God has abandoned us. %s",
		"There is nothing you can do to amend this. %s.",
		"Great job! %s",
		"You sure did that. %s",
		"Rise above, %s.",
		"YOU DID WHAT?!?!?!?! %s",
		"%s adds to the counter. God help us all.",
		"%s rises by one. Pray.",
		"%s doesn’t even know the implications of what they just did.",
		"You will regret this, %s.",
		"%s Did you wash your hands?",
		"%s I hope you had fun!",
		"%s You seriously need to work on your aim.",
		"%s May the piss be ever in your favor.",
		"%s The piss goes IN the jar, NOT ON it.",
		"Get help. %s",
		"%s Pissing all by yourself handsome? ;)",
		"%s What would you be without The Pissening™",
		"%s Alright now go top up on some water we got pissing to do.",
		"%s Pick it up piss boy.",
		"%s I saw that.",
		"Piss.",
		"%s Feel better?",
		"%s Another day another piss.",
		"%s [REDACTED]",
		"%s Are you pissing CURRENTLY or did you just finish?",
		"%s Staying hydrated, huh?",
		"%s You can relax. For now.",
		"The fates press on, %s",
		"%s Was this strategy or simple impulse?",
		"%s Your piss has been recorded.",
		"%s Drink more water.",
		"%s Urination acknowledged.",
		"%s How much longer must we suffer?",
		"%s No escape. No escape. No escap&. No ^sc4pe. N0 e$%93. N9 #%D>8E..",
		"%s Press on.",
		"%s You know what you must do.",
		"%s Don't forget why you're here.. Why you fight.",
		"%s Win.",
		"%s What a pissin piss pisser!",
		"%s LETS GOOOO!",
		"%s Part of the ship, part of the crew.",
		"%s Man, great job pal!",
		"Presenting our next pisser, %s!",
		"Your bravery is appreciated, gladiator %s.",
		"You honor your name in your sacrifice, %s.",
		"%s How much longer can you press on?",
		"%s One more, one more, one mo6e, o5e m%r#, 0£^ 4+&3",
		"%s The level rises..",
		"%s You have completed your quest.. You must continue onto the next one.",
		"%s I see you threw in some pissazz with that one",
		"%s Be thinking of your next move.",
		"%s You dig further into the hole. Do not get stuck in it.",
		"%s Holy pissoli.",
		"%s Piss on.",
		"%s A good piss for a good cause.",
		"%s Another pissifice for The Jar.",
		"%s Will you go on as a pissgressor or a pissifist?",
		"%s You can flush away your piss, but can you flush away the things you've done.",
	}
)
